name: DVC pipeline

on:
  workflow_dispatch:

#Enable docker services with dind
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          #python3 -m venv venv
          #cd venv
          #. ./bin/activate
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
          pip uninstall -y boto3
          pip install boto3==1.35.*
          pip list | grep boto3
          aws --version
      - name: Initialization
        run: |
          git init
          dvc init -f
          git config --global user.email "dkarpov.legal@gmail.com"
          git config --global user.name "dkarpov.legal"
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.YANDEX_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.YANDEX_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION="ru-central1"
      - name: DVC remote configuration
        run: |
          mkdir -p data code

          dvc remote add yandexs3 s3://mynewbucket
          dvc remote modify yandexs3 endpointurl https://storage.yandexcloud.net
          dvc remote modify yandexs3 --local access_key_id {{secrets.YANDEX_ACCESS_KEY_ID}}
          dvc remote modify yandexs3 --local secret_access_key {{secrets.YANDEX_SECRET_ACCESS_KEY}}
          dvc remote modify yandexs3 --local region ru-central1
          dvc remote list
          dvc import-url https://pjreddie.com/media/files/mnist_train.csv data/train_data.csv
          dvc import-url https://pjreddie.com/media/files/mnist_test.csv data/test_data.csv
          git status -s
          cat data/.gitignore
          git status -s data/*
          cat data/.gitignore
          git add .
          git commit -m 'Adding files for DVC'
          dvc add data/test_data.csv
          dvc add data/train_data.csv



